name: Gaming
# Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
# hide-desktop-navigation: true
slug: gaming
title: Gaming
center-vertically: true
expand-mobile-page-navigation: true
show-mobile-header: true
columns:
  - $include: ../myColumns/left.yml
  - size: full
    widgets:
      - $include: ../myWidgets/search.yml
      - $include: ../myWidgets/epicGamesFreeGames.yml
      - $include: ../myWidgets/steamRecentlyPlayed.yml
      - $include: ../myWidgets/steamSpecials.yml
      - $include: ../myWidgets/steamTopSellers.yml
      - $include: ../myWidgets/gamingSubreddits.yml
  - $include: ../myColumns/right.yml
